export interface DocumentPreview {
  blobUrl: string | null
  type: 'word' | 'pdf'
  title: string
  loading: boolean
  error: string
}

/**
 * Word documents are generated by the Nitro export endpoint. PDFs are
 * generated in the browser via pdfmake so no server-side PDF converter
 * (e.g. LibreOffice) is required — this keeps the app deployable to
 * serverless hosts like Laravel Cloud.
 */
export function useDocumentExport() {
  const previewDoc = ref<DocumentPreview | null>(null)

  async function openExport(content: string, type: 'word' | 'pdf', title: string) {
    previewDoc.value = { blobUrl: null, type, title, loading: true, error: '' }

    try {
      const blob = type === 'pdf' ? await buildPdfLocally(content, title) : await buildWordFromServer(content, title)

      if (previewDoc.value?.blobUrl) {
        URL.revokeObjectURL(previewDoc.value.blobUrl)
      }

      previewDoc.value = { blobUrl: URL.createObjectURL(blob), type, title, loading: false, error: '' }
    } catch (err: any) {
      previewDoc.value = { blobUrl: null, type, title, loading: false, error: err?.message ?? 'Could not load the export.' }
    }
  }

  function closePreview() {
    if (previewDoc.value?.blobUrl) {
      URL.revokeObjectURL(previewDoc.value.blobUrl)
    }
    previewDoc.value = null
  }

  return {
    previewDoc,
    openExport,
    closePreview,
  }
}

async function buildWordFromServer(content: string, title: string): Promise<Blob> {
  const response = await fetch('/api/documents/export', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/octet-stream',
    },
    body: JSON.stringify({ content, title }),
  })

  if (!response.ok) {
    const errBody = await response.json().catch(() => null)
    throw new Error(errBody?.message ?? `Export failed (HTTP ${response.status})`)
  }

  return response.blob()
}

async function buildPdfLocally(content: string, title: string): Promise<Blob> {
  const { buildPdfBlob } = await import('~/utils/pdf')
  return buildPdfBlob(content, title)
}
