import { authHeaders } from '~/lib/http'
import { useSupabase } from '~/lib/supabase'

/** Narrowest the preview panel may be dragged before it stops shrinking. */
export const MIN_PREVIEW_WIDTH = 320

export interface DocumentPreview {
  blobUrl: string | null
  type: 'word' | 'pdf'
  title: string
  loading: boolean
  error: string
}

/**
 * Word documents are generated by the Nitro export endpoint. PDFs are
 * generated in the browser via pdfmake so no server-side PDF converter
 * (e.g. LibreOffice) is required — this keeps the app deployable to
 * serverless hosts like Laravel Cloud.
 *
 * Drafts produced from an uploaded .docx template are exempt: they are always
 * exported server-side, where the original template file is filled and
 * converted (Word and PDF), so the exported file keeps the template's logo
 * and formatting.
 */
export function useDocumentExport() {
  const {
    public: { apiBase },
  } = useRuntimeConfig()

  const previewDoc = ref<DocumentPreview | null>(null)

  // Width of the desktop preview panel. Draggable via the panel's left-edge
  // handle. The optional getter caps how far the panel may grow so it never
  // crosses into the main chat area.
  const previewWidth = ref(450)

  function startResize(event: PointerEvent, getMaxWidth?: () => number) {
    event.preventDefault()

    const startX = event.clientX
    const startWidth = previewWidth.value
    const viewportLimit = Math.max(window.innerWidth - 24, MIN_PREVIEW_WIDTH)

    // The panel renders the document in a blob-URL iframe, which is a separate
    // document: without capture, dragging inward puts the cursor over the
    // iframe and its document swallows the pointermove events, so the drag
    // stalls until the cursor leaves again. Capturing pins every move to the
    // handle no matter what it passes over.
    const handle = event.currentTarget instanceof Element ? event.currentTarget : null

    handle?.setPointerCapture?.(event.pointerId)

    // Resolved once, on pointer down. The space available to the panel cannot
    // change while the pointer is held, and re-reading it on every move meant
    // measuring a sibling that had already been resized by the previous move —
    // the panel's own width fed back into its own limit, so the drag
    // oscillated instead of stopping at the boundary.
    const maxWidth = Math.min(
      viewportLimit,
      getMaxWidth ? Math.max(getMaxWidth(), MIN_PREVIEW_WIDTH) : viewportLimit,
    )

    // pointermove fires far faster than the display refreshes, and each write
    // triggers a re-layout of the panel and the PDF frame inside it. Coalesce
    // to one write per frame so the drag tracks the pointer smoothly.
    let frame = 0
    let nextWidth = startWidth

    const commit = () => {
      frame = 0
      previewWidth.value = nextWidth
    }

    const onMove = (e: PointerEvent) => {
      nextWidth = Math.min(Math.max(startWidth + (startX - e.clientX), MIN_PREVIEW_WIDTH), maxWidth)

      if (frame === 0) {
        frame = requestAnimationFrame(commit)
      }
    }

    const onUp = () => {
      if (frame !== 0) {
        cancelAnimationFrame(frame)
        frame = 0
      }

      previewWidth.value = nextWidth

      if (handle?.hasPointerCapture?.(event.pointerId)) {
        handle.releasePointerCapture(event.pointerId)
      }

      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
      window.removeEventListener('pointercancel', onUp)
      document.body.style.cursor = ''
      document.body.style.userSelect = ''
    }

    document.body.style.cursor = 'col-resize'
    document.body.style.userSelect = 'none'
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp, { once: true })
    // Capture is lost if the browser cancels the gesture (an OS window switch,
    // a touch turning into a scroll); without this the drag state and the
    // body's cursor/user-select overrides would be left stuck.
    window.addEventListener('pointercancel', onUp, { once: true })
  }

  async function openExport(content: string, type: 'word' | 'pdf', title: string, messageId?: string) {
    previewDoc.value = { blobUrl: null, type, title, loading: true, error: '' }

    try {
      const blob = messageId
        ? await buildFromMessage(messageId, type)
        : type === 'pdf'
          ? await buildPdfLocally(content, title)
          : await buildWordFromServer(content, title)

      if (previewDoc.value?.blobUrl) {
        URL.revokeObjectURL(previewDoc.value.blobUrl)
      }

      previewDoc.value = { blobUrl: URL.createObjectURL(blob), type, title, loading: false, error: '' }
    } catch (err: any) {
      previewDoc.value = { blobUrl: null, type, title, loading: false, error: err?.message ?? 'Could not load the export.' }
    }
  }

  function closePreview() {
    if (previewDoc.value?.blobUrl) {
      URL.revokeObjectURL(previewDoc.value.blobUrl)
    }
    previewDoc.value = null
  }

  async function downloadExport(content: string, type: 'word' | 'pdf', title: string, messageId?: string) {
    const blob = messageId
      ? await buildFromMessage(messageId, type)
      : type === 'pdf'
        ? await buildPdfLocally(content, title)
        : await buildWordFromServer(content, title)
    const url = URL.createObjectURL(blob)

    const link = document.createElement('a')
    link.href = url
    link.download = `${title}.${type === 'pdf' ? 'pdf' : 'docx'}`
    document.body.appendChild(link)
    link.click()
    link.remove()

    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  return {
    previewDoc,
    previewWidth,
    startResize,
    openExport,
    closePreview,
    downloadExport,
  }
}

async function buildFromMessage(messageId: string, type: 'word' | 'pdf'): Promise<Blob> {
  const {
    public: { apiBase },
  } = useRuntimeConfig()

  const request = async () =>
    fetch(`${apiBase}/api/messages/${messageId}/export/${type}`, {
      method: 'POST',
      headers: await authHeaders({ Accept: 'application/octet-stream' }),
    })

  let response = await request()

  // An expired access token is the one retryable failure here: refresh once
  // and repeat before surfacing an export error.
  if (response.status === 401) {
    const { data } = await useSupabase().auth.refreshSession()

    if (data.session) {
      response = await request()
    }
  }

  if (!response.ok) {
    const errBody = await response.json().catch(() => null)
    throw new Error(errBody?.message ?? `Export failed (HTTP ${response.status})`)
  }

  return response.blob()
}

async function buildWordFromServer(content: string, title: string): Promise<Blob> {
  const response = await fetch('/api/documents/export', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/octet-stream',
    },
    body: JSON.stringify({ content, title }),
  })

  if (!response.ok) {
    const errBody = await response.json().catch(() => null)
    throw new Error(errBody?.message ?? `Export failed (HTTP ${response.status})`)
  }

  return response.blob()
}

async function buildPdfLocally(content: string, title: string): Promise<Blob> {
  const { buildPdfBlob } = await import('~/utils/pdf')
  return buildPdfBlob(content, title)
}
