export interface DocumentPreview {
  blobUrl: string | null
  type: 'word' | 'pdf'
  title: string
  loading: boolean
  error: string
}

/**
 * Word documents are generated by the Nitro export endpoint. PDFs are
 * generated in the browser via pdfmake so no server-side PDF converter
 * (e.g. LibreOffice) is required — this keeps the app deployable to
 * serverless hosts like Laravel Cloud.
 */
export function useDocumentExport() {
  const previewDoc = ref<DocumentPreview | null>(null)

  // Width of the desktop preview panel. Draggable via the panel's left-edge
  // handle. The optional getter caps how far the panel may grow so it never
  // crosses into the main chat area.
  const previewWidth = ref(450)

  function startResize(event: PointerEvent, getMaxWidth?: () => number) {
    event.preventDefault()

    const startX = event.clientX
    const startWidth = previewWidth.value
    const viewportLimit = Math.max(window.innerWidth - 24, 320)

    const onMove = (e: PointerEvent) => {
      const desired = startWidth + (startX - e.clientX)
      const upper = getMaxWidth ? Math.max(getMaxWidth(), 320) : viewportLimit
      previewWidth.value = Math.min(Math.max(desired, 320), Math.min(viewportLimit, upper))
    }

    const onUp = () => {
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
      document.body.style.cursor = ''
      document.body.style.userSelect = ''
    }

    document.body.style.cursor = 'col-resize'
    document.body.style.userSelect = 'none'
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp, { once: true })
  }

  async function openExport(content: string, type: 'word' | 'pdf', title: string) {
    previewDoc.value = { blobUrl: null, type, title, loading: true, error: '' }

    try {
      const blob = type === 'pdf' ? await buildPdfLocally(content, title) : await buildWordFromServer(content, title)

      if (previewDoc.value?.blobUrl) {
        URL.revokeObjectURL(previewDoc.value.blobUrl)
      }

      previewDoc.value = { blobUrl: URL.createObjectURL(blob), type, title, loading: false, error: '' }
    } catch (err: any) {
      previewDoc.value = { blobUrl: null, type, title, loading: false, error: err?.message ?? 'Could not load the export.' }
    }
  }

  function closePreview() {
    if (previewDoc.value?.blobUrl) {
      URL.revokeObjectURL(previewDoc.value.blobUrl)
    }
    previewDoc.value = null
  }

  async function downloadExport(content: string, type: 'word' | 'pdf', title: string) {
    const blob = type === 'pdf' ? await buildPdfLocally(content, title) : await buildWordFromServer(content, title)
    const url = URL.createObjectURL(blob)

    const link = document.createElement('a')
    link.href = url
    link.download = `${title}.${type === 'pdf' ? 'pdf' : 'docx'}`
    document.body.appendChild(link)
    link.click()
    link.remove()

    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  return {
    previewDoc,
    previewWidth,
    startResize,
    openExport,
    closePreview,
    downloadExport,
  }
}

async function buildWordFromServer(content: string, title: string): Promise<Blob> {
  const response = await fetch('/api/documents/export', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/octet-stream',
    },
    body: JSON.stringify({ content, title }),
  })

  if (!response.ok) {
    const errBody = await response.json().catch(() => null)
    throw new Error(errBody?.message ?? `Export failed (HTTP ${response.status})`)
  }

  return response.blob()
}

async function buildPdfLocally(content: string, title: string): Promise<Blob> {
  const { buildPdfBlob } = await import('~/utils/pdf')
  return buildPdfBlob(content, title)
}
