<script setup lang="ts">
import { CheckIcon, CircleIcon, ClockIcon, TrashIcon } from '@lucide/vue'
import { useTodoStore, type Todo } from '~/stores/todos'

definePageMeta({
  middleware: ['auth', 'organization', 'subscription'],
})

const todoStore = useTodoStore()
const api = useApi()
const router = useRouter()

const statusFilter = ref<'all' | 'pending' | 'on-going' | 'completed'>('all')
const conversations = ref<Array<{ id: string; title: string | null }>>([])
const conversationFilter = ref<string>('all')
const loadingConversations = ref(false)

const filteredTodos = computed(() =>
  todoStore.todos.filter((t) => {
    if (statusFilter.value !== 'all' && t.status !== statusFilter.value) return false
    if (conversationFilter.value !== 'all' && t.conversation_id !== conversationFilter.value) return false
    return true
  })
)

const counts = computed(() => ({
  all: todoStore.todos.length,
  pending: todoStore.todos.filter((t) => t.status === 'pending').length,
  'on-going': todoStore.todos.filter((t) => t.status === 'on-going').length,
  completed: todoStore.todos.filter((t) => t.status === 'completed').length,
}))

const statusStyles: Record<Todo['status'], string> = {
  pending: 'bg-muted text-muted-foreground',
  'on-going': 'bg-peach/60 text-espresso dark:bg-cream/10 dark:text-peach',
  completed: 'bg-forest/10 text-forest dark:bg-cream/10 dark:text-peach',
}

const statusLabel: Record<Todo['status'], string> = {
  pending: 'Pending',
  'on-going': 'On-going',
  completed: 'Completed',
}

const priorityStyles: Record<string, string> = {
  low: 'bg-muted text-muted-foreground',
  medium: 'bg-espresso/10 text-espresso dark:bg-cream/10 dark:text-peach',
  high: 'bg-destructive/10 text-destructive dark:bg-cream/10 dark:text-destructive',
}

function statusIcon(status: Todo['status']) {
  return status === 'completed' ? CheckIcon : status === 'on-going' ? ClockIcon : CircleIcon
}

function conversationTitle(id: string) {
  return conversations.value.find((c) => c.id === id)?.title || 'Conversation'
}

async function loadConversations() {
  loadingConversations.value = true
  try {
    const { data } = await api<{ data: Array<{ id: string; title: string | null }> }>('/conversations')
    conversations.value = data
  } catch {
    conversations.value = []
  } finally {
    loadingConversations.value = false
  }
}

async function openConversation(id: string) {
  await router.push({ path: '/chat', query: { c: id } })
}

onMounted(async () => {
  await Promise.all([todoStore.fetchTodos(), loadConversations()])
})
</script>

<template>
  <div class="mx-auto w-full max-w-5xl px-4 py-6">
    <PageHeader
      title="Next Steps"
      description="Action items generated by the AI for your legal matters."
    >
      <template #actions>
        <Select v-model="conversationFilter">
          <SelectTrigger class="w-56 text-sm">
            <SelectValue :placeholder="'All conversations'" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All conversations</SelectItem>
            <SelectItem v-for="c in conversations" :key="c.id" :value="c.id">
              {{ c.title || 'Untitled' }}
            </SelectItem>
          </SelectContent>
        </Select>

        <Select v-model="statusFilter">
          <SelectTrigger class="w-40 text-sm">
            <SelectValue :placeholder="'All statuses'" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All statuses ({{ counts.all }})</SelectItem>
            <SelectItem value="pending">Pending ({{ counts.pending }})</SelectItem>
            <SelectItem value="on-going">On-going ({{ counts['on-going'] }})</SelectItem>
            <SelectItem value="completed">Completed ({{ counts.completed }})</SelectItem>
          </SelectContent>
        </Select>
      </template>
    </PageHeader>

    <ListSkeleton v-if="todoStore.loading || loadingConversations" :rows="4" :icon="false" />

    <EmptyState
      v-else-if="filteredTodos.length === 0"
      :icon="CircleIcon"
      title="No action items found"
      description="Ask the assistant to draft a legal document and it will generate the next steps for you."
    />

    <div v-else class="space-y-2">
      <div
        v-for="todo in filteredTodos"
        :key="todo.id"
        class="group flex items-start gap-3 rounded-lg border bg-card p-4 transition-colors hover:bg-muted/50"
      >
        <button
          type="button"
          :aria-label="`Change status of “${todo.title}” (currently ${statusLabel[todo.status]})`"
          :class="statusStyles[todo.status]"
          class="mt-0.5 shrink-0 rounded-full p-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
          @click="todoStore.toggleStatus(todo.id)"
        >
          <component :is="statusIcon(todo.status)" class="size-4" />
        </button>

        <div class="min-w-0 flex-1">
          <p class="text-sm font-medium leading-tight">{{ todo.title }}</p>
          <div class="mt-1.5 flex flex-wrap items-center gap-2">
            <Badge :class="statusStyles[todo.status]" class="text-[10px]">
              {{ statusLabel[todo.status] }}
            </Badge>
            <Badge v-if="todo.priority" :class="priorityStyles[todo.priority]" class="text-[10px]">
              {{ todo.priority }}
            </Badge>
            <span v-if="todo.due_hint" class="text-[11px] text-muted-foreground">
              {{ todo.due_hint }}
            </span>
            <button
              class="text-[11px] text-primary hover:underline"
              @click="openConversation(todo.conversation_id)"
            >
              {{ conversationTitle(todo.conversation_id) }}
            </button>
          </div>
        </div>

        <button
          type="button"
          :aria-label="`Delete action item: ${todo.title}`"
          class="shrink-0 rounded p-1 text-muted-foreground opacity-0 transition-opacity hover:text-destructive focus-visible:opacity-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50 group-hover:opacity-100"
          @click="todoStore.deleteTodo(todo.id)"
        >
          <TrashIcon class="size-4" />
        </button>
      </div>
    </div>
  </div>
</template>
