<script setup lang="ts">
import { ArrowLeftIcon, GitBranchIcon, PlusIcon } from '@lucide/vue'
import { toast } from '~/components/ui/sonner'
import type { Pipeline, PipelineOutcome, PipelineStage } from '~/types/pipeline'
definePageMeta({ middleware: ['auth', 'onboarding', 'subscription', 'terms'] })
const store = usePipelineStore(); const selected = ref<Pipeline | null>(null); const name = ref(''); const loading = ref(true); const loadingError = ref<unknown>(null); const status = (e: unknown) => store.statusOf(e)
async function load() { loading.value = true; loadingError.value = null; try { await store.fetchPipelines() } catch (e) { loadingError.value = e } finally { loading.value = false } }
onMounted(load)
async function create() { if (!name.value.trim()) return; try { const pipeline = await store.createPipeline({ name: name.value.trim() }); name.value = ''; await load(); selected.value = pipeline; toast.success('Pipeline created.') } catch { toast.error('Could not create the pipeline. Your draft is still here.') } }
async function refresh() { if (selected.value) { selected.value = await store.fetchPipeline(selected.value.id); await load() } }
async function addStage(stageName: string, outcome_kind: PipelineOutcome) { try { await store.createStage(selected.value!.id, { name: stageName, outcome_kind }); await refresh() } catch { toast.error('Could not add the stage.') } }
async function rename(stage: PipelineStage, stageName: string) { try { await store.updateStage(selected.value!.id, stage.id, { name: stageName, outcome_kind: stage.outcome_kind }); await refresh() } catch { toast.error('Could not rename the stage.') } }
async function archive(stage: PipelineStage) { if (!confirm(`Archive “${stage.name}”? Any active items must be reassigned before this stage can be archived.`)) return; try { await store.archiveStage(selected.value!.id, stage.id); await refresh() } catch (e) { toast.error((e as { data?: { message?: string } })?.data?.message ?? 'This stage cannot be archived until its items are reassigned.') } }
async function restore(stage: PipelineStage) { try { await store.restoreStage(selected.value!.id, stage.id); await refresh() } catch { toast.error('Could not restore the stage.') } }
async function reorder(ids: string[]) { try { await store.reorderStages(selected.value!.id, ids); await refresh() } catch { toast.error('Could not save the stage order.') } }
</script>
<template><main class="mx-auto w-full max-w-5xl px-4 pt-8 pb-6 sm:px-6"><AppPageHeader title="Pipeline settings" description="Configure intake pipelines and their ordered stages." :icon="GitBranchIcon"><template #breadcrumb><NuxtLink to="/crm" class="hover:text-foreground">CRM</NuxtLink><span aria-hidden="true"> / </span>Pipelines</template><template #actions><NuxtLink to="/crm" class="inline-flex min-h-11 items-center gap-1.5 rounded-lg border px-3 text-sm font-medium hover:bg-muted"><ArrowLeftIcon class="size-4" /> Back to intake</NuxtLink></template></AppPageHeader><div v-if="loadingError" class="surface-inset mt-5 py-14 text-center"><h2 class="text-lg font-semibold">Pipelines could not load</h2><p class="mt-2 text-sm text-muted-foreground">{{ status(loadingError) === 403 ? 'You do not have permission to configure pipelines.' : 'Check your connection and try again.' }}</p><Button v-if="status(loadingError) !== 403" variant="outline" class="mt-5 min-h-11" @click="load">Retry</Button></div><template v-else><div class="mt-5 grid gap-5 lg:grid-cols-[17rem_1fr]"><section class="surface p-4"><div class="flex items-center justify-between gap-2"><h2 class="font-semibold">Pipelines</h2><span class="text-xs text-muted-foreground">{{ store.pipelines.length }}</span></div><form class="mt-4 flex gap-2" @submit.prevent="create"><Input v-model="name" aria-label="New pipeline name" placeholder="New pipeline" class="h-10 min-w-0" /><Button type="submit" size="icon" class="size-10 shrink-0" :disabled="!name.trim()" aria-label="Create pipeline"><PlusIcon class="size-4" /></Button></form><div class="mt-4 grid gap-1"><button v-for="pipeline in store.pipelines" :key="pipeline.id" type="button" class="rounded-lg p-3 text-left text-sm transition-colors hover:bg-muted" :class="selected?.id === pipeline.id ? 'bg-primary/10 font-semibold text-primary' : ''" @click="selected = pipeline"><span class="block">{{ pipeline.name }}</span><span class="mt-1 block text-xs font-normal text-muted-foreground">{{ pipeline.stages.filter(s => !s.archived_at).length }} active stages</span></button><p v-if="!store.pipelines.length && !store.loading" class="py-5 text-center text-sm text-muted-foreground">No pipelines yet. Create one to begin.</p></div></section><div><div v-if="store.loading" class="grid gap-3"><Skeleton v-for="i in 4" :key="i" class="h-14 rounded-xl" /></div><PipelineStageManager v-else-if="selected" :pipeline="selected" :busy="store.saving" @create="addStage" @rename="rename" @reorder="reorder" @archive="archive" @restore="restore" /><div v-else class="surface-inset py-16 text-center"><GitBranchIcon class="mx-auto size-7 text-muted-foreground" /><h2 class="mt-3 font-semibold">Choose a pipeline</h2><p class="mt-2 text-sm text-muted-foreground">Create a pipeline or select one to manage its stages.</p></div></div></div></template></main></template>
